<?php
require __DIR__.'/../app/bootstrap.php'; require_login();
$types=['computer'=>'رایانه','printer'=>'چاپگر','display'=>'نمایشگر','scanner'=>'اسکنر'];
$q=trim((string)($_GET['q']??'')); $type=(string)($_GET['type']??''); $status=(string)($_GET['status']??'');
$page=max(1,(int)($_GET['page']??1)); $perPage=20; $where=[];$params=[];
if($q!==''){ $where[]='(a.asset_no LIKE ? OR a.hostname LIKE ? OR a.manufacturer LIKE ? OR a.model LIKE ? OR a.serial_no LIKE ? OR p.full_name LIKE ?)'; for($i=0;$i<6;$i++)$params[]='%'.$q.'%'; }
if(isset($types[$type])){$where[]='a.asset_type=?';$params[]=$type;} if(in_array($status,['active','repair','retired','lost'],true)){$where[]='a.status=?';$params[]=$status;}
$sqlWhere=$where?'WHERE '.implode(' AND ',$where):'';
$st=db()->prepare("SELECT COUNT(*) FROM assets a LEFT JOIN personnel p ON p.id=a.personnel_id $sqlWhere");$st->execute($params);$total=(int)$st->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$offset=($page-1)*$perPage;
$st=db()->prepare("SELECT a.*,p.full_name personnel_name FROM assets a LEFT JOIN personnel p ON p.id=a.personnel_id $sqlWhere ORDER BY a.updated_at DESC LIMIT $perPage OFFSET $offset");$st->execute($params);$rows=$st->fetchAll();
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>تجهیزات</title><link rel="stylesheet" href="assets/app.css"></head><body><header><a class="brand" href="index.php">سامانه سخت‌افزار</a><nav><a href="assets.php">تجهیزات</a><?php if((user()['role']??'')==='admin'):?><a href="personnel.php">پرسنل</a><a href="audit.php">رویدادها</a><?php endif;?><a href="logout.php">خروج</a></nav></header><main><div class="page-head"><div><h1>فهرست تجهیزات</h1><p class="muted">جستجو، فیلتر و مشاهده سوابق تجهیزات</p></div><?php if(can_edit_assets()):?><a class="btn primary" href="asset_new.php">+ ثبت مورد جدید</a><?php endif;?></div><form class="filters" method="get"><input name="q" value="<?=e($q)?>" placeholder="شماره اموال، نام دستگاه، مدل، سریال یا پرسنل"><select name="type"><option value="">همه انواع</option><?php foreach($types as $k=>$v):?><option value="<?=$k?>" <?=$type===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select><select name="status"><option value="">همه وضعیت‌ها</option><?php foreach(['active'=>'فعال','repair'=>'تعمیر','retired'=>'اسقاط','lost'=>'مفقود'] as $k=>$v):?><option value="<?=$k?>" <?=$status===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select><button class="btn">اعمال</button></form><div class="table-wrap"><table><thead><tr><th>شماره اموال</th><th>نوع</th><th>نام دستگاه</th><th>برند / مدل</th><th>پرسنل</th><th>مکان</th><th>وضعیت</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=e($r['asset_no'])?></strong></td><td><?=e($types[$r['asset_type']]??$r['asset_type'])?></td><td><?=e($r['hostname']??'—')?></td><td><?=e(trim(($r['manufacturer']??'').' '.($r['model']??''))?:'—')?></td><td><?=e($r['personnel_name']??'—')?></td><td><?=e($r['location']??'—')?></td><td><span class="badge <?=$r['status']?>"><?=e(['active'=>'فعال','repair'=>'تعمیر','retired'=>'اسقاط','lost'=>'مفقود'][$r['status']]??$r['status'])?></span></td><td><a class="btn small" href="asset_view.php?asset_no=<?=urlencode($r['asset_no'])?>">مشاهده</a></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="8" class="empty">موردی یافت نشد.</td></tr><?php endif;?></tbody></table></div><div class="pagination"><span>صفحه <?=$page?> از <?=$pages?> — <?=$total?> مورد</span><?php if($page>1):?><a href="?<?=http_build_query(array_merge($_GET,['page'=>$page-1]))?>">قبلی</a><?php endif;?><?php if($page<$pages):?><a href="?<?=http_build_query(array_merge($_GET,['page'=>$page+1]))?>">بعدی</a><?php endif;?></div></main></body></html>
