<?php
require __DIR__.'/../app/bootstrap.php'; require_role(['admin']); require_once __DIR__.'/../app/Services/ActiveDirectory.php'];
$error=null;$message=null;
$cfg=db()->query('SELECT * FROM ad_settings WHERE id=1')->fetch() ?: ['host'=>'','port'=>389,'use_tls'=>0,'base_dn'=>'','bind_dn'=>'','bind_password_enc'=>'','user_filter'=>'(&(objectCategory=person)(objectClass=user))'];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$action=$_POST['action']??'';
 if($action==='save'){$host=trim((string)$_POST['host']);$port=max(1,(int)$_POST['port']);$base=trim((string)$_POST['base_dn']);$bind=trim((string)$_POST['bind_dn']);$filter=trim((string)$_POST['user_filter']);$enc=$cfg['bind_password_enc']??null;if((string)($_POST['bind_password']??'')!=='')$enc=encrypt_secret((string)$_POST['bind_password']);if($host===''||$base===''||$bind===''||$filter==='')throw new RuntimeException('آدرس، Base DN، حساب اتصال و فیلتر الزامی هستند.');$st=db()->prepare('INSERT INTO ad_settings(id,host,port,use_tls,base_dn,bind_dn,bind_password_enc,user_filter,updated_by) VALUES(1,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE host=VALUES(host),port=VALUES(port),use_tls=VALUES(use_tls),base_dn=VALUES(base_dn),bind_dn=VALUES(bind_dn),bind_password_enc=VALUES(bind_password_enc),user_filter=VALUES(user_filter),updated_by=VALUES(updated_by)');$st->execute([$host,$port,isset($_POST['use_tls'])?1:0,$base,$bind,$enc,$filter,user()['id']]);audit('ad_settings_updated','directory','1',[]);$message='تنظیمات Active Directory ذخیره شد.';$cfg=db()->query('SELECT * FROM ad_settings WHERE id=1')->fetch();}
 elseif($action==='test'||$action==='sync'){$current=db()->query('SELECT * FROM ad_settings WHERE id=1')->fetch();if(!$current)throw new RuntimeException('ابتدا تنظیمات اتصال را ذخیره کنید.');$current['bind_password']=decrypt_secret($current['bind_password_enc']??null);$ad=new ActiveDirectory($current);if($action==='test'){$message=$ad->test()['message'];audit('ad_connection_test','directory','1',[]);}else{$n=$ad->sync();$message="همگام‌سازی انجام شد: {$n} رکورد پرسنلی دریافت/به‌روزرسانی شد.";audit('ad_personnel_sync','directory','1',['count'=>$n]);}}
}catch(Throwable $e){$error=$e->getMessage();}}
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Active Directory</title><link rel="stylesheet" href="assets/app.css"></head><body><header><a class="brand" href="index.php">سامانه سخت‌افزار</a><nav><a href="index.php">داشبورد</a><a href="assets.php">تجهیزات</a><a href="users.php">کاربران برداشت</a><a href="personnel.php">پرسنل</a><a href="audit.php">رویدادها</a><a href="logout.php">خروج</a></nav></header><main><div class="page-head"><div><h1>اتصال به Active Directory</h1><p class="muted">پرسنل از دایرکتوری خوانده و در جدول داخلی برای انتخاب مسئول تجهیز همگام می‌شوند.</p></div></div><?php if($error):?><div class="alert danger"><?=e($error)?></div><?php endif;?><?php if($message):?><div class="alert success"><?=e($message)?></div><?php endif;?><section class="panel"><h2>تنظیم اتصال</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><label>نام/IP سرور AD<input name="host" value="<?=e($cfg['host']??'')?>" required placeholder="dc.example.local"></label><label>Port<input type="number" name="port" value="<?=e((string)($cfg['port']??389))?>" min="1" max="65535"></label><label>Base DN<input name="base_dn" value="<?=e($cfg['base_dn']??'')?>" required placeholder="DC=example,DC=local"></label><label>Bind DN / User<input name="bind_dn" value="<?=e($cfg['bind_dn']??'')?>" required placeholder="CN=svc-ihw,OU=Service Accounts,DC=example,DC=local"></label><label>رمز حساب اتصال<input type="password" name="bind_password" placeholder="<?=($cfg['bind_password_enc']??'')?'ذخیره شده؛ برای تغییر وارد کنید':''?>"></label><label>LDAP Filter<input name="user_filter" value="<?=e($cfg['user_filter']??'(&(objectCategory=person)(objectClass=user))')?>"></label><label class="check"><input type="checkbox" name="use_tls" value="1" <?=!empty($cfg['use_tls'])?'checked':''?>> استفاده از LDAPS</label><div class="actions"><button class="btn primary">ذخیره تنظیمات</button></div></form></section><section class="panel"><h2>عملیات دایرکتوری</h2><div class="actions"><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="test"><button class="btn">تست اتصال</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="sync"><button class="btn primary">همگام‌سازی پرسنل از AD</button></form></div><p class="muted">در همگام‌سازی، employeeID و در نبود آن sAMAccountName به‌عنوان کد پرسنلی استفاده می‌شود؛ نام، اداره و سمت نیز خوانده می‌شوند.</p></section></main></body></html>
