<?php
require __DIR__.'/../app/bootstrap.php'; require_role(['admin']);
$search=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['page']??1));$per=25;$where='';$args=[];
if($search!==''){$where='WHERE full_name LIKE ? OR first_name LIKE ? OR last_name LIKE ? OR national_id LIKE ? OR mobile LIKE ? OR personnel_code LIKE ? OR department LIKE ? OR position LIKE ?';$like='%'.$search.'%';$args=[$like,$like,$like,$like,$like,$like,$like,$like];}
$q=db()->prepare("SELECT * FROM personnel {$where} ORDER BY last_name,first_name,full_name LIMIT {$per} OFFSET ".(($page-1)*$per));$q->execute($args);$rows=$q->fetchAll();$cq=db()->prepare("SELECT COUNT(*) FROM personnel {$where}");$cq->execute($args);$total=(int)$cq->fetchColumn();$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$success=flash('success');$danger=flash('danger');
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>پرسنل</title><link rel="stylesheet" href="assets/app.css"></head><body><header><a class="brand" href="index.php">سامانه سخت‌افزار</a><nav><a href="index.php">داشبورد</a><a href="assets.php">تجهیزات</a><a href="directory.php">Active Directory</a><a href="users.php">کاربران برداشت</a><a href="audit.php">رویدادها</a><a href="logout.php">خروج</a></nav></header><main><div class="page-head"><div><h1>پرسنل</h1><p class="muted">اطلاعات دستی/فایلی با کدملی یکتا مدیریت می‌شود و تجهیزات هر فرد در پرونده او قابل مشاهده است.</p></div><div class="actions"><a class="btn primary" href="personnel_import.php">ورود از فایل CSV</a><a class="btn" href="directory.php">تنظیم / همگام‌سازی AD</a></div></div>
<?php if($success):?><div class="alert success"><?=e($success)?></div><?php endif;?><?php if($danger):?><div class="alert danger"><?=e($danger)?></div><?php endif;?>
<section class="panel"><form class="search"><input name="q" value="<?=e($search)?>" placeholder="جستجوی نام، کدملی، تلفن همراه، کد پرسنلی، اداره یا سمت"><button class="btn">جستجو</button></form><div class="table-wrap"><table><thead><tr><th>نام</th><th>نام خانوادگی</th><th>کدملی</th><th>تلفن همراه</th><th>کد پرسنلی</th><th>تجهیزات</th><th>عملیات</th></tr></thead><tbody>
<?php foreach($rows as $r):?><tr><td><?=e($r['first_name']?:'—')?></td><td><?=e($r['last_name']?:$r['full_name'])?></td><td><strong><?=e($r['national_id']?:'—')?></strong></td><td><?=e($r['mobile']?:'—')?></td><td><?=e($r['personnel_code']?:'—')?></td><td><a class="btn small" href="personnel_assets.php?id=<?=$r['id']?>">مشاهده تجهیزات</a></td><td><div class="actions" style="margin:0"><a class="btn small" href="personnel_edit.php?id=<?=$r['id']?>">ویرایش</a><form method="post" action="personnel_delete.php" onsubmit="return confirm('این پرسنل حذف شود؟ مسئولیت تجهیزات او خالی خواهد شد.');"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn small danger">حذف</button></form></div></td></tr><?php endforeach;?>
<?php if(!$rows):?><tr><td colspan="7" class="empty">رکوردی یافت نشد.</td></tr><?php endif;?></tbody></table></div><div class="pagination"><span>صفحه <?=$page?> از <?=$pages?> — <?=$total?> نفر</span><?php if($page>1):?><a href="?<?=e(http_build_query(array_merge($_GET,['page'=>$page-1])))?>">قبلی</a><?php endif;?><?php if($page<$pages):?><a href="?<?=e(http_build_query(array_merge($_GET,['page'=>$page+1])))?>">بعدی</a><?php endif;?></div></section></main></body></html>
