<?php
require __DIR__.'/../app/bootstrap.php'; require_role(['admin']);
$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $action=$_POST['action']??'';
 try{
  if($action==='save'){
   $id=(int)($_POST['id']??0); $username=trim((string)($_POST['username']??'')); $full=trim((string)($_POST['full_name']??'')); $role=(int)($_POST['role_id']??0); $pass=(string)($_POST['password']??''); $active=isset($_POST['is_active'])?1:0;
   if(!preg_match('/^[A-Za-z0-9._-]{3,100}$/',$username)) throw new RuntimeException('نام کاربری نامعتبر است.');
   if($full==='') throw new RuntimeException('نام و نام خانوادگی الزامی است.');
   $rs=db()->prepare('SELECT id,name FROM roles WHERE id=?'); $rs->execute([$role]); $r=$rs->fetch(); if(!$r) throw new RuntimeException('نقش انتخاب‌شده معتبر نیست.');
   if($id){ $old=db()->prepare('SELECT username,role_id,is_active FROM users WHERE id=?');$old->execute([$id]);$u=$old->fetch();if(!$u) throw new RuntimeException('کاربر یافت نشد.');
    if($u['username']===(user()['username']??'') && (!$active || $r['name']!=='admin')) throw new RuntimeException('کاربر مدیر فعلی نمی‌تواند غیرفعال یا از نقش مدیر خارج شود.');
    $sql='UPDATE users SET username=?,full_name=?,role_id=?,is_active=?';$args=[$username,$full,$role,$active]; if($pass!==''){if(strlen($pass)<8)throw new RuntimeException('رمز عبور باید حداقل ۸ کاراکتر باشد.');$sql.=',password_hash=?';$args[]=password_hash($pass,PASSWORD_DEFAULT);} $sql.=' WHERE id=?';$args[]=$id;db()->prepare($sql)->execute($args);audit('user_updated','user',(string)$id,['username'=>$username]);flash('success','کاربر به‌روزرسانی شد.');
   } else {if(strlen($pass)<8)throw new RuntimeException('رمز عبور باید حداقل ۸ کاراکتر باشد.');$st=db()->prepare('INSERT INTO users(username,password_hash,full_name,role_id,is_active) VALUES(?,?,?,?,?)');$st->execute([$username,password_hash($pass,PASSWORD_DEFAULT),$full,$role,$active]);audit('user_created','user',(string)db()->lastInsertId(),['username'=>$username,'role'=>$r['name']]);flash('success','کاربر ایجاد شد.');}
  }
 }catch(Throwable $e){$error=$e->getMessage();}
}
$edit=null;if(isset($_GET['edit'])){$q=db()->prepare('SELECT id,username,full_name,role_id,is_active FROM users WHERE id=?');$q->execute([(int)$_GET['edit']]);$edit=$q->fetch();}
$roles=db()->query('SELECT id,name,title FROM roles ORDER BY id')->fetchAll();
$users=db()->query('SELECT u.id,u.username,u.full_name,u.is_active,u.created_at,u.updated_at,r.title role_title,r.name role_name FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.id DESC')->fetchAll();
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>مدیریت کاربران</title><link rel="stylesheet" href="assets/app.css"></head><body><header><a class="brand" href="index.php">سامانه سخت‌افزار</a><nav><a href="index.php">داشبورد</a><a href="assets.php">تجهیزات</a><a href="personnel.php">پرسنل</a><a href="audit.php">رویدادها</a><a href="logout.php">خروج</a></nav></header><main><div class="page-head"><div><h1>مدیریت کاربران و نقش‌ها</h1><p class="muted">کنترل دسترسی چهار نقش سامانه</p></div></div><?php if($error):?><div class="alert danger"><?=e($error)?></div><?php endif;?><?php if($m=flash('success')):?><div class="alert success"><?=e($m)?></div><?php endif;?><section class="panel"><h2><?=$edit?'ویرایش کاربر':'ایجاد کاربر جدید'?></h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=$edit['id']??0?>"><label>نام کاربری<input name="username" value="<?=e($edit['username']??'')?>" required></label><label>نام و نام خانوادگی<input name="full_name" value="<?=e($edit['full_name']??'')?>" required></label><label>نقش<select name="role_id" required><?php foreach($roles as $r):?><option value="<?=$r['id']?>" <?=((int)($edit['role_id']??0)===(int)$r['id'])?'selected':''?>><?=e($r['title'])?></option><?php endforeach;?></select></label><label>رمز عبور <?=$edit?'(در صورت تغییر)':''?><input type="password" name="password" minlength="8" <?=$edit?'':'required'?>></label><label class="check"><input type="checkbox" name="is_active" value="1" <?=(!$edit||$edit['is_active'])?'checked':''?>> حساب فعال</label><div class="actions"><button class="btn primary">ذخیره</button><?php if($edit):?><a class="btn" href="users.php">لغو و ایجاد جدید</a><?php endif;?></div></form></section><section class="panel"><h2>کاربران</h2><div class="table-wrap"><table><thead><tr><th>نام کاربری</th><th>نام</th><th>نقش</th><th>وضعیت</th><th>آخرین بروزرسانی</th><th></th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?=e($u['username'])?></td><td><?=e($u['full_name'])?></td><td><?=e($u['role_title'])?></td><td><span class="badge <?=$u['is_active']?'ok':'muted-badge'?>"><?=$u['is_active']?'فعال':'غیرفعال'?></span></td><td><?=e($u['updated_at'])?></td><td><a class="btn small" href="users.php?edit=<?=$u['id']?>">ویرایش</a></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
