<?php
declare(strict_types=1);
$config=require __DIR__.'/../config/config.php';date_default_timezone_set($config['app']['timezone']);session_name($config['security']['session_name']);session_set_cookie_params(['httponly'=>true,'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','samesite'=>'Lax']);session_start();
if(!headers_sent()){header('X-Frame-Options: SAMEORIGIN');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: strict-origin-when-cross-origin');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');}
$pdo=new PDO($config['db']['dsn'],$config['db']['user'],$config['db']['pass'],$config['db']['options']);
function db():PDO{global $pdo;return $pdo;}function app_config():array{global $config;return $config;}function e(?string $v):string{return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}function url(string $path=''):string{global $config;return ($config['app']['base_url']??'').'/'.ltrim($path,'/');}function redirect(string $path):never{header('Location: '.url($path));exit;}function csrf_token():string{if(empty($_SESSION['_csrf']))$_SESSION['_csrf']=bin2hex(random_bytes(32));return $_SESSION['_csrf'];}function verify_csrf():void{if(!hash_equals($_SESSION['_csrf']??'',$_POST['_csrf']??'')){http_response_code(419);exit('درخواست نامعتبر است.');}}function user():?array{return $_SESSION['user']??null;}function require_login():void{if(!user())redirect('login.php');}function require_role(array $roles):void{require_login();if(!in_array(user()['role']??'',$roles,true)){http_response_code(403);exit('دسترسی غیرمجاز');}}function can_edit_assets():bool{return in_array(user()['role']??'', ['admin','collector','expert'],true);}
function can_manage_asset_type(string $type,string $action='edit'):bool{if(!in_array($type,['computer','printer','display','scanner'],true))return false;if((user()['role']??'')==='admin')return true;if(!can_edit_assets())return false;try{$q=db()->prepare('SELECT can_create,can_edit FROM user_asset_permissions WHERE user_id=? AND asset_type=?');$q->execute([(int)(user()['id']??0),$type]);$p=$q->fetch();if(!$p)return true;return (bool)$p[$action==='create'?'can_create':'can_edit'];}catch(Throwable $e){return true;}}
function secret_key():string{global $config;return hash('sha256',(string)(getenv('IHW_APP_KEY')?:($config['db']['pass'].'|ihw-directory-secret')),true);}function encrypt_secret(string $value):string{$iv=random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);return base64_encode($iv.sodium_crypto_secretbox($value,$iv,secret_key()));}function decrypt_secret(?string $value):string{if(!$value)return '';try{$raw=base64_decode($value,true);if($raw===false||strlen($raw)<=SODIUM_CRYPTO_SECRETBOX_NONCEBYTES)return '';return sodium_crypto_secretbox_open(substr($raw,SODIUM_CRYPTO_SECRETBOX_NONCEBYTES),substr($raw,0,SODIUM_CRYPTO_SECRETBOX_NONCEBYTES),secret_key())?:'';}catch(Throwable $e){return '';}}
function upload_storage_dir():string{static $dir=null;if($dir!==null)return $dir;$configured=trim((string)(getenv('IHW_UPLOAD_DIR')?:''));$dir=$configured!==''?$configured:dirname(__DIR__).'/storage/uploads';if((!is_dir($dir)&&@mkdir($dir,0700,true))||is_dir($dir)&&is_writable($dir))return $dir;$fallback=rtrim(sys_get_temp_dir(),DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.'ihw-uploads';if(!is_dir($fallback))@mkdir($fallback,0700,true);if(!is_dir($fallback)||!is_writable($fallback))throw new RuntimeException('مسیر ذخیره فایل قابل نوشتن نیست.');$dir=$fallback;return $dir;}
function audit(string $action,?string $entityType=null,?string $entityId=null,array $details=[]):void{$st=db()->prepare('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,ip_address,user_agent,details) VALUES(?,?,?,?,?,?,?)');$st->execute([user()['id']??null,$action,$entityType,$entityId,$_SERVER['REMOTE_ADDR']??null,substr($_SERVER['HTTP_USER_AGENT']??'',0,500),json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}function flash(string $key,?string $value=null):?string{if($value!==null){$_SESSION['_flash'][$key]=$value;return null;}$v=$_SESSION['_flash'][$key]??null;unset($_SESSION['_flash'][$key]);return $v;}
